export const carData = [
    {
      marca: "Ford",
      modelos: [
        "Fiesta",
        "Focus",
        "Mustang",
        "Escape",
        "Explorer",
        "Expedition",
        "F-150",
        "Ranger",
        "Edge",
        "Bronco",
      ],
    },
    {
      marca: "Toyota",
      modelos: [
        "Camry",
        "Corolla",
        "Rav4",
        "Highlander",
        "Prius",
        "Tacoma",
        "Tundra",
        "Sienna",
        "4Runner",
        "Land Cruiser",
      ],
    },
    {
      marca: "Honda",
      modelos: [
        "Civic",
        "Accord",
        "CR-V",
        "Pilot",
        "Odyssey",
        "Fit",
        "HR-V",
        "Ridgeline",
        "Insight",
        "Clarity",
      ],
    },
    {
      marca: "Chevrolet",
      modelos: [
        "Cruze",
        "Malibu",
        "Equinox",
        "Traverse",
        "Tahoe",
        "Suburban",
        "Silverado",
        "Colorado",
        "Blazer",
        "Camaro",
      ],
    },
    {
      marca: "BMW",
      modelos: [
        "3 Series",
        "5 Series",
        "7 Series",
        "X1",
        "X3",
        "X5",
        "X7",
        "Z4",
        "M2",
        "i8",
      ],
    },
  ]

  export const carColors = ['Vermelho', 'Azul', 'Verde', 'Preto', 'Branco', 'Prata', 'Amarelo', 'Laranja', 'Roxo', 'Cinza'];